version: '3'

services:
  flask-dev:
    build:
      context: .
      dockerfile: docker/flask-dev/Dockerfile
    environment:
      - PORT=${PORT}
      - FLASK_ENV=dev
    ports:
      - 8090:80
    volumes:
      - .:/project
    working_dir: /project/python
    command: poetry run python main.py

  flask:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    environment:
      - PORT=${PORT}
    ports:
      - 8091:80
