name: CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: prepare secrets
        run: |
          mkdir -p config/account
          echo $GOOGLE_CLOUD_KEY > config/account/api-test.json
        env:
          GOOGLE_CLOUD_KEY: ${{ secrets.GOOGLE_CLOUD_KEY }}

      - name: pytest
        run: docker compose run --rm test
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ../config/account/api-test.json
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PORT: 8080

  flake8:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: flake8
        run: docker compose run --rm flake8

  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: mypy
        run: docker compose run --rm mypy
